# Generated by Django 4.0.1 on 2022-03-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_meeting_calendar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='host',
            field=models.CharField(default='', max_length=50),
        ),
    ]
